name: Build
on: [push]
jobs:
  build-win:
    runs-on: windows-latest
    outputs:
      digest: ${{steps.upload-win.outputs.artifact-digest}}
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: nuget restore "CM Launcher.sln"

    - name: Build CML
      working-directory: ./Windows
      run: |
        dotnet build --configuration Release
        mv "bin/Release/CM Launcher.exe" "bin/Release/CML.exe"

    - uses: actions/upload-artifact@v7
      id: upload-win
      with:
        name: 'CML.exe'
        path: Windows/bin/Release/CML.exe
        archive: false
  build-osx:
    runs-on: macos-13
    outputs:
      digest: ${{steps.upload-osx.outputs.artifact-digest}}

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: latest
        xamarin-mac-version: latest
        xcode-version: latest

    - name: Restore NuGet Packages
      run: nuget restore "CM Launcher.sln"

    - name: Build CML
      working-directory: ./OSX
      run: |
        msbuild /property:Configuration=Release
        mkdir -p zip
        mv bin/Release/CML.app zip/CML.app
        chmod +x zip/CML.app/Contents/MacOS/CML

    - uses: papeloto/action-zip@v1
      with:
        files: OSX/zip
        dest: CML.app.zip

    - uses: actions/upload-artifact@v7
      id: upload-osx
      with:
        name: 'CML.app.zip'
        path: CML.app.zip
        archive: false
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{steps.upload-linux.outputs.artifact-digest}}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Environment
      run: |
        sudo add-apt-repository -syn universe
        sudo apt-get update
        sudo apt-get install dotnet-sdk-10.0
          
    - name: Build CML
      working-directory: ./Linux
      run: |
        dotnet publish -c Release --sc -r linux-x64

    - uses: actions/upload-artifact@v7
      id: upload-linux
      with:
        name: 'CML-Linux'
        path: Linux/bin/Release/net6.0/linux-x64/publish/CML-Linux
        archive: false

  version-file:
    runs-on: ubuntu-latest
    needs: [build-osx, build-win, build-linux]
    steps:
    - uses: actions/checkout@v2

    - name: Write version file
      run: grep -Po 'APP_VERSION = \K[0-9]+' Shared/Config.cs | tr -d '\n' > cml

    - uses: actions/upload-artifact@v7
      with:
        name: 'cml'
        path: cml
        archive: false

  index-file:
    runs-on: ubuntu-latest
    needs: [build-osx, build-win, build-linux]
    steps:
    - name: Parse config file
      uses: edgardleal/mustache-template-action@v1.0.0
      env:
        LINUX_HASH: ${{needs.build-linux.outputs.digest}}
      with:
        input: index.mo
        output: index.html

    - uses: actions/upload-artifact@v7
      with:
        name: 'index.html'
        path: index.html
        archive: false
